data:
  root: ~/data/MNIST
  image_shape: [1, 28, 28]
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

model:
  type: unet
  in_channels: 1
  base_channels: 96

ema:
  decay: 0.9999
  warmup: crowsonkb
  inv_gamma: 1.0
  power: 0.75

training:
  max_steps: 10000
  precision: fp32
  global_batch_size: 256  # across GPUs and accumulation steps
  micro_batch_size: -1    # samples per GPU per forward pass
  gradient_clip: 1.0

optimizer:
  type: adamw
  lr: 0.001
  betas: [0.9, 0.99]
  weight_decay: 0.01

scheduler:
  type: constant-warmup
  warmup_steps: 1000

checkpoint:
  every_steps: 2000

logging:
  every_steps: 100

sampling:
  every_steps: 1000
  num_samples: 64
  nfe: 50
